name: sauna
on:
  push:
    branches:
      - main
    paths:
      - sauna/**
  pull_request:
    paths:
       - sauna/**
jobs:
  npm:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        node: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
        working-directory: ./sauna
      - run: npm test
        working-directory: ./sauna
